# Generated by Django 4.1 on 2022-09-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ap', models.CharField(max_length=50)),
                ('nom_padre', models.CharField(max_length=50)),
                ('nom_madre', models.CharField(max_length=50)),
                ('nom_hijo', models.CharField(max_length=50)),
                ('padres_nac', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('ap', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('nac', models.CharField(max_length=20)),
            ],
        ),
    ]
