# Generated by Django 4.1 on 2022-08-31 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_hijo_madre_padre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ap', models.CharField(max_length=50)),
                ('nom_padre', models.CharField(max_length=50)),
                ('nom_madre', models.CharField(max_length=50)),
                ('nom_hijo', models.CharField(max_length=50)),
                ('padres_nac', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='familiar',
        ),
        migrations.RenameField(
            model_name='hijo',
            old_name='apellido',
            new_name='ap',
        ),
        migrations.RenameField(
            model_name='hijo',
            old_name='edad',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='madre',
            old_name='apellido',
            new_name='ap',
        ),
        migrations.RenameField(
            model_name='madre',
            old_name='edad',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='padre',
            old_name='apellido',
            new_name='ap',
        ),
        migrations.RenameField(
            model_name='padre',
            old_name='edad',
            new_name='nom',
        ),
        migrations.RemoveField(
            model_name='hijo',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='madre',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='padre',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='hijo',
            name='nac',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='madre',
            name='nac',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='padre',
            name='nac',
            field=models.CharField(max_length=20),
        ),
    ]
